config/routes.rb
Rails.application.routes.draw do 
  devise_for :users
  root to: "users#index"
  
  resources :users, only: [:show, :index]
  get 'comments/create'
  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :author, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 250 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments
  validates :content, presence: true, length: { maximum: 250 }
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_one_attached :avatar


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      format.html { redirect_to @post }
      format.js {}
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
 
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @posts = Post.order(created_at: :desc).limit(10).paginate(:page => params[:page], :per_page => 10)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post.liked_by @user
    @post.unliked_by @user
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  private

    def set_post
      @post = Post.find(params[:id])
    end
 
    def post_params
      params.require(:post).permit(:content, :user_id, images: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  def index
     @users = User.all
  end



  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end


  private
    def set_user
      @user = User.find(params[:id])
    end
   
    def user_params
      params.require(:user).permit(:name,:avatar)
    end
end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
  <p>
    <strong><%= comment.author %></strong> said:
  </p>
  <p>
    <%= comment.body %>
  </p>
</li>

app/views/comments/_form.html.erb
<%= form_with scope: :comment, url: [@post, @post.comments.build], local: true do |f| %>
    <div>
      Author: <%= f.text_field :author %>
    </div>
    <div>
      Text: <%= f.text_area :body %>
    </div>

    <%= f.submit %>
<% end %>

app/views/comments/create.js.erb
$("#comments").append("<%= j render @comment %>");
$("#comment_author").val("");
$("#comment_body").val("");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   


   <nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
    <div class="container">
      <h4> Posts</h4>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="navbar-nav ml-auto">
              <div class="navbar-nav ml-auto">
                <% if user_signed_in? %>
            <div class="nav-item">
                <span class="navbar-text">
                  Hello, &nbsp;
                  <span>
                  </div>
                  <div class="dropdown show">
                    <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                  </div>
                  <div>
                  <% else %>
                      <div class="nav-item">
                         <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                      </div>
                      <div class="nav-item">
                         <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                      </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
</nav>
 <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
 <div class="container">
      <%= yield %>
 </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, rows: '3', cols: '30' %>
  </div>

  <div>
  <%= form.label :images, "Загрузить фото" %>
  <%= form.file_field :images, multiple: true %> <br />
  <div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="form-group">
    <h4>Edit post</h4>

    <%= render 'form', post: @post %>

    <%= link_to 'Show', @post, class: "btn btn-primary" %> |
    <%= link_to 'Back', posts_path, class: "btn btn-primary" %>

  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
<table >
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
     
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td scope="col"><%= post.content %></td>
        <td scope="col"><%= link_to post.user.name, user_path(post.user.id)%></td>
         <td><%= link_to 'Show', post, class: "btn btn-outline-primary" %></td>
        
        <% if current_user == post.user  %>
           <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary" %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-outline-primary" %></td>
        <% end %>
      </tr>
    <% end %>
    <td><%= will_paginate @posts %></td>
  </tbody>
</table>
</div>
<br>

app/views/posts/new.html.erb
<div class="container">
 <div class="form-group">
  <h4>New post</h4>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path, class: "btn btn-primary" %>
</div>
</div>

app/views/posts/show.html.erb
<div class="container">
<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<div class="flex-parent">
  <% @post.images.each do |image| %>
  <%= image_tag image, size: 200 %> 
  <%end%>
</div>  
</br>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary " %>
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>


<h2><%= link_to 'Comments', '#', id: 'comments-link' %></h2>
  <div id="comment-section">
    <ol id="comments">
      <%= render @post.comments %>
    </ol>

  <h3>Add a comment:</h3>
  <%= render 'comments/form' %>
</div>


</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
         <td> <%= image_tag user.avatar, size: 100 if user.avatar.attached? %></td>
        <td><%= link_to user.name, user  %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="container">
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
     
    </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
  <td><%= post.content %> </td>
  <% if current_user == post.user  %>
          <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary" %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-outline-primary" %></td>
        <% end %>
  </br>
  <%end%>

</tbody>
<% if current_user == @user  %>
  <%= link_to 'New Post', new_post_path , class: "btn btn-primary mb-2" %> 
<%end%>
</br>

<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

</div>

 <%= will_paginate @posts %>